#!/bin/bash

set -e

pushd "$(dirname "$0")" > /dev/null
SCRIPT_DIR="$(pwd)"
popd > /dev/null
SRC_DIR=$SCRIPT_DIR/src
TGT_DIR=$SCRIPT_DIR/tgt

clang                       \
	-o $TGT_DIR/sndfilter   \
	-fwrapv                 \
	-Werror                 \
	$SRC_DIR/main.c         \
	$SRC_DIR/wav.c          \
	$SRC_DIR/biquad.c       \
	$SRC_DIR/compressor.c
